# Generated by Django 4.1.2 on 2022-10-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('fdc_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nutrient_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('food', models.ForeignKey(db_column='fdc_id', on_delete=django.db.models.deletion.CASCADE, to='food.food', to_field='fdc_id')),
                ('nutrient', models.ForeignKey(db_column='nutrient_id', on_delete=django.db.models.deletion.CASCADE, to='food.nutrient', to_field='nutrient_id')),
            ],
        ),
    ]
