# Generated by Django 4.1.2 on 2022-10-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodnutrients',
            name='unit_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='unit_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
